version: '3.8'
services:
  mysql:
    image: mysql:8.0.41-debian
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "ecommerce"
    volumes:
      - ./docker_data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"