#spring.application.name=csdl
spring:
  application:
    name:csdl
  datasource:
    url: "jdbc:mysql://localhost:3306/ecommerce?allowPublicKeyRetrieval=true&useSSL=false"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true